[tools]
rust = "nightly"
bun = "latest"


[tasks.install]
description = "Install hj from local"
run = "cargo install --path . --force"

[tasks.lint]
description = "Run linters"
run = "cargo clippy --fix --allow-no-vcs"

[tasks.docs]
description = "Run docs"
run = [
  "bun install --no-cache",
  "bun run docs:dev",
]
dir = "docs"



[tasks.stat]
description = "Stat code lines"
run = "tokei ."
dir = "src"

[tasks.ci]
depends = ["lint"]

[tasks.post_commit]
depends = ["install"]
